-- AlterTable
ALTER TABLE "Pet" ADD COLUMN     "vetId" TEXT;

-- AddForeignKey
ALTER TABLE "Pet" ADD CONSTRAINT "Pet_vetId_fkey" FOREIGN KEY ("vetId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
